### ISSUE TITLE
API design for `delete file` feature

### ISSUE THREAD

**Issue by shivaken** [moata/kokoUpload#3]
Your API design looks like following RESTful API design. 
But only this API is not really similar to that.

If you change this `delete file` API to more like RESTful API, what kind of endpoint will it be?
I feel there might be suitable URL and HTTP method for that.
Could you create a branch like `development` and push only document change to the branch?(You don't need to update the implementation itself)

**Comment by moata** [comment]
I believe using the HTTP DELETE method. branch development created and new code pushed to the branch.
